#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $INFRAO_ADMIN with login password '$INFRAO_ADMIN_PASSWORD';  
    CREATE DATABASE $INFRAO_DB;
    GRANT ALL PRIVILEGES ON DATABASE $INFRAO_DB TO $INFRAO_ADMIN;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$INFRAO_DB" <<-EOSQL
    CREATE EXTENSION postgis;
EOSQL