name: Render to HTML
on:
  pull_request:

jobs:
  render:
    name: Render to HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Render Rmd to HTML
        run: ./render.sh
      - name: Move output to docs
        run: rm -rf docs/* && cp -r out/* docs/
      - name: Assert index.html exists
        run: test -f docs/index.html
